env: dev
migrations_path: ./migrations

jwt:
  access_token_lifetime: 1h
  refresh_token_lifetime: 168h

database:
  host: db
  port: 5432
  user: jwt-user
  name: jwt-auth
  password: jwt333
  timeout: 5s
  attempts: 5
  delay: 5s

http_server:
  port: 8080
  timeout: 5s
  idle_timeout: 1m