env: local
migrations_path: ./migrations

jwt:
  access_token_lifetime: 1h
  refresh_token_lifetime: 168h

database:
  host: localhost
  port: 5432
  user: postgres
  name: jwt-auth
  password: postgres
  timeout: 5s
  attempts: 5
  delay: 5s

http_server:
  port: 8080
  timeout: 5s
  idle_timeout: 1m